name: compu_cuantica
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pip:
      - qiskit
      - qiskit-ibm-runtime
      - pylatexenc
      - matplotlib
      - numpy
      - scipy
      - sympy
